config/routes.rb
Rails.application.routes.draw do
  resources :monuments
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monument.rb
class Monument < ApplicationRecord
  validates :name, length: { minimum: 3 }
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController
  before_action :set_monument, only: %i[ show edit update destroy ]

  # GET /monuments
  def index
    @monuments = Monument.all
    @monument = Monument.new
  end

  # GET /monuments/1
  def show
  end

  # GET /monuments/new
  def new
    @monument = Monument.new
  end

  # GET /monuments/1/edit
  def edit
  end

  # POST /monuments
  def create
    @monument = Monument.new(monument_params)

    respond_to do |format|
      if @monument.save
        format.html { redirect_to @monument, notice: "Monument was successfully created." }
        format.json # regular rails flow!  will look for create.json
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json # regular rails flow!  will look for create.json
      end
    end

  end

  # PATCH/PUT /monuments/1
  def update
    if @monument.update(monument_params)
      redirect_to @monument, notice: "Monument was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /monuments/1
  def destroy
    @monument.destroy!
    redirect_to monuments_url, notice: "Monument was successfully destroyed.", status: :see_other
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_monument
    @monument = Monument.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def monument_params
    params.require(:monument).permit(:name, :address, :opening_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JavascriptInRails1685</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/monuments/_form.html.erb
<%# data-action='submit->form-submit#method' %>
<%= simple_form_for(@monument,
                    data: {
                      action: 'submit->form-submit#send',
                      form_submit_target: 'form'
                    }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :opening_date, input_html: { data: { controller: 'datepicker'}}, as: :string %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/monuments/_monument.html.erb
<div id="<%= dom_id monument %>">
  <p>
    <strong>Name:</strong>
    <%= monument.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= monument.address %>
  </p>

  <p>
    <strong>Opening date:</strong>
    <%= monument.opening_date %>
  </p>

</div>

<p>
  <%= link_to "Show this monument", monument %>
</p>

app/views/monuments/edit.html.erb
<h1>Editing monument</h1>

<%= render "form", monument: @monument %>

<br>

<div>
  <%= link_to "Show this monument", @monument %> |
  <%= link_to "Back to monuments", monuments_path %>
</div>

app/views/monuments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Monuments</h1>

<div data-controller='form-submit'>
  <div id="monuments" data-form-submit-target="list">
    <% @monuments.each do |monument| %>
      <%= render monument %>
    <% end %>

    <%# add the new monument %>
  </div>
  <%#= link_to "New monument", new_monument_path %>
  data-controller MUST HAVE ACCESS TO THE TARGETS AND ACTIONS
  <div data-controller='insert-in-list'>
    <button class="btn btn-primary" data-action='click->insert-in-list#send'>New monument</button>
    <div data-insert-in-list-target="toggable" class="d-none">
      <%= render 'form', monument: @monument %>
    </div>
  </div>
</div>

app/views/monuments/new.html.erb
<h1>New monument</h1>

<%= render "form", monument: @monument %>

<br>

<div>
  <%= link_to "Back to monuments", monuments_path %>
</div>

app/views/monuments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @monument %>

<div>
  <%= link_to "Edit this monument", edit_monument_path(@monument) %> |
  <%= link_to "Back to monuments", monuments_path %>

  <%= button_to "Destroy this monument", @monument, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>